name: Build and Tests

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
          - os: ubuntu-latest
            c_compiler: clang
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "tests=${{ github.workspace }}/tests/testing_" >> "$GITHUB_OUTPUT"
    
    - name: Configure CMake for testing maths
      working-directory: ${{ steps.strings.outputs.tests }}maths
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
    
    - name: Build testing maths
      working-directory: ${{ steps.strings.outputs.tests }}maths
      run: cmake --build build --config Release
    
    - name: Running testing maths
      working-directory: ${{ steps.strings.outputs.tests }}maths
      run: ctest --test-dir build -C Release --output-on-failure
    
    - name: Configure CMake for testing strings
      working-directory: ${{ steps.strings.outputs.tests }}strings
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
    
    - name: Build testing strings
      working-directory: ${{ steps.strings.outputs.tests }}strings
      run: cmake --build build --config Release
    
    - name: Running testing strings
      working-directory: ${{ steps.strings.outputs.tests }}strings
      run: ctest --test-dir build -C Release --output-on-failure
